controllers/refreshTokenController.js, middlewares/authenticateToken.js, routes/refreshToken.js
added refreshTokenController, refreshToken route and authenticateToken middleware
=> added JWT authentication

controllers/registerController.js, middlewares/reCaptcha.js
=> add some adjustment

controllers/loginController.js, controllers/registerController.js, routes/login.js
=> add login router and loginController

frontend/src/App.jsx, frontend/src/components/Login/Login.css, frontend/src/components/Login/Login.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/Register/Register.jsx, frontend/src/index.css
modification of the login, register , navbar, homepage and app.jsx in order to integrate the login process and the proper navigation through all the components sending props to each component
=> Editingcomponents

controllers/registerController.js
=> validation added to password

controllers/loginController.js, controllers/moodController.js, controllers/registerController.js, controllers/userController.js, models/Mood.js, models/User.js, routes/mood.js, routes/user.js
=> Mood model, create mood route, add mood route added

controllers/travelController.js
=> fixed import in travel controller

controllers/travelController.js, frontend/src/views/TravelMood.css, frontend/src/views/TravelMood.jsx, models/Recommendation.js, seeder.js
updated recommendation model, updated travel view to fetch data from the backend
=> Travel view

controllers/userController.js, routes/user.js
=> mood route updated

controllers/userController.js, frontend/src/components/MoodTracker/MoodTracker.jsx
=> added changes

frontend/src/App.jsx, frontend/src/components/DestinationView/DestinationView.css, frontend/src/components/DestinationView/DestinationView.jsx, frontend/src/components/Layout/Layout.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/TravelMood/TravelMood.css, frontend/src/components/TravelMood/TravelMood.jsx, frontend/src/views/PageNotFound.css, frontend/src/views/PageNotFound.jsx
creation of the destination view , pagenotfound css to make it visible, as well i made some changes on the app.jsx and the travel mood component, navbar to make possible for the user after logout come back to the homepage using useNavigation implementing a handle Logout function properly , please review the changes and let me know just the mood tracker keeps having issues on my local repo.
=> new component added for the destination view

controllers/userController.js, frontend/src/App.jsx, frontend/src/components/MoodTracker/MoodTracker.css, frontend/src/components/MoodTracker/MoodTracker.jsx
=> MoodTracker updated

frontend/src/App.jsx, frontend/src/components/MoodTracker/MoodTracker.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/TravelMood/TravelMood.jsx, frontend/src/components/UserProfile/UserProfile.jsx, frontend/src/context/Context.jsx, routes/user.js
=> Context Updated

frontend/src/context/Context.jsx
=> problem solved

frontend/src/components/UserProfile/UserProfile.jsx
here is the the component modified according to the wireframes
=> new user profile modified

frontend/src/context/Context.jsx, routes/user.js
=> Authentication has been added to the frontend

controllers/cookiesController.js, frontend/src/context/Context.jsx, routes/resetCookies.js, server.js
=> reset Cookies added

frontend/src/components/UserProfile/UserProfile.css, frontend/src/components/UserProfile/UserProfile.jsx, frontend/src/context/Context.jsx
new version of the user profile with the dropdown added, icons and buttons included, and the inputs corrected added, provisional styling for further changes
=> Userprofile v3

frontend/src/App.jsx, frontend/src/components/Contact/Contact.css, frontend/src/components/Contact/Contact.jsx, frontend/src/components/Footer/Footer.css, frontend/src/components/Footer/Footer.jsx, frontend/src/components/Layout/Layout.jsx
creation of contact form and footer components
=> new components contact and footer

frontend/package-lock.json, frontend/package.json, frontend/src/components/Contact/Contact.jsx, frontend/src/context/Context.jsx
I added the code and functionalities of the contact form using emailjs i putted all the functions inside of the context  to keep the order and structure of our code( i already tested  it),  in order to visualize it and make it work you have to install first the library running on your terminal this command: "npm install emailjs-com", i used for now my dci email account but we can change it after.
=> Contact form code completed

frontend/src/components/DestinationView/DestinationView.jsx
=> destination veiw updated

frontend/src/components/MoodPreview.jsx, frontend/src/components/MoodTracker/MoodTracker.jsx
correction of the route inside of the button element of the mood preview now redirecting correctly to the component
=> correction of the navigation button in the mood preview

frontend/src/components/Footer/Footer.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/tailwind.config.js
minor cosmetic defects but works perfectly fine whilst being responsive. As soon as Alexis tells me their thoughts on it tomorrow I will give it the final touch.
=> Ok, footer and navbar are pretty much done. The navbar has a few

frontend/src/components/Navbar/Navbar.jsx
=> scroll hide added to nav

frontend/src/components/Navbar/Navbar.jsx
=> nav updated

frontend/src/components/Navbar/Navbar.jsx, frontend/src/context/Context.jsx
=> navbar updated

frontend/src/components/Navbar/Navbar.jsx, package-lock.json, package.json
=> nav improved

frontend/src/components/Contact/Contact.jsx, frontend/src/components/DestinationView/DestinationView.jsx, frontend/src/components/MoodTracker/MoodTracker.jsx, frontend/src/components/TravelCategories.jsx, frontend/src/components/TravelDestinations.jsx, frontend/src/components/TravelEmotions.jsx, frontend/src/components/TravelMood/TravelMood.jsx, frontend/src/context/Context.jsx
=> Scroll behavior updated
